Switch rewrites for tree-unique-args
egraphs-good/eggcc pull request #223
Opened 2024-01-10 23:27 UTC by Alex-Fischman

- Ran `cargo fmt` to autoformat. (This is responsible for most of the diff; we should consider adding `cargo fmt --check` to our CI.)
- Ran `cargo clippy --tests` and fixed a bunch of warnings.
  - Disabled the [`useless_format` lint](https://rust-lang.github.io/rust-clippy/master/index.html#/useless_format).
- Added my (now extremely simple) optimization.
- Added tests.
- Changed rewrites to birewrites because it was trivial; this makes this optimization better than it was in past schemas!

2024-01-10 23:54 UTC, yihozhang approved these changes
LGTM!

2024-01-11 15:41 UTC, oflatt requested changes
Thanks for fixing clippy! Yes, please add those checks to CI 
Very nice rewrites too

2024-01-11 16:45 UTC, oflatt commented on tree_unique_args/src/switch_rewrites.rs
> +(birewrite (Switch (And a b) (Cons A (Cons B (Nil))))
No I think because `b` might not be evaluated if `a` is true
Unless the semantics of `And` are short-circuiting (I think they are not)

2024-01-11 17:59 UTC, Alex-Fischman commented on tree_unique_args/src/switch_rewrites.rs
> +(birewrite (Switch (And a b) (Cons A (Cons B (Nil))))
Why does `a` need to be pure if it's always evaluated?

2024-01-11 21:00 UTC, oflatt commented on tree_unique_args/src/switch_rewrites.rs
> +(birewrite (Switch (And a b) (Cons A (Cons B (Nil))))
You are right, only `b` need be pure

2024-01-11 22:22 UTC, oflatt approved these changes
Great job! Good purity test

2024-01-11 22:22 UTC, merged