Add util.egg
egraphs-good/eggcc pull request #245
Opened 2024-01-12 10:06 UTC by clyben

Add util.egg, which contains ListExpr-length and ListExpr-ith function.

2024-01-12 16:08 UTC, oflatt requested changes
Looks good! I think you have a typo

2024-01-12 16:08 UTC, oflatt commented on tree_unique_args/src/util.egg
> +(function ListExpr-surfix (ListExpr i64) ListExpr :unextractable)
Typo: I think you meant "suffix"

2024-01-12 20:28 UTC, clyben commented on tree_unique_args/src/util.egg
> +(function ListExpr-surfix (ListExpr i64) ListExpr :unextractable)
ohh....(

2024-01-15 17:56 UTC, oflatt approved these changes
Thanks!
For future reference, after you fix up a PR don't forget to re-request a review.

2024-01-15 17:56 UTC, merged