Memory ops for RVSDG => Bril
egraphs-good/eggcc pull request #353
Opened 2024-02-13 07:47 UTC by ezrosent

Wire in memory ops in to_cfg. Opening a draft as there are a few questions in to_cfg I'd like to resolve.

Fixes #343

2024-02-13 19:33 UTC, oflatt requested changes
Nice work!
Is this tested by the current infra? I think you need to say that the RVSDG roundtrip run mode supports memory.

2024-02-13 19:33 UTC, oflatt commented on src/rvsdg/to_cfg.rs
> +                // TODO: should we combine these?
remove todo, comment that we combine all but the state edge

2024-02-14 05:08 UTC, ezrosent commented
Done! This uncovered a preexisting issue with converting empty functions:

```
@funcA(p: ptr<int>) {
  ret;
}

@main {
  five: int = const 5;
  x: ptr<int> = alloc five;
  call @funcA x;
  free x;
}
```

Gets translated back correctly, but `@funcA` had an empty body

```
@funcA(p: ptr<int>) {
}
```

Which caused the bril interpreter to panic. I added some code to fix that.

2024-02-14 17:30 UTC, oflatt approved these changes
Great!

2024-02-16 04:50 UTC, merged