Substitution with fuel
egraphs-good/eggcc pull request #448
Opened 2024-04-11 00:19 UTC by oflatt

2024-04-11 21:07 UTC, kirstenmg commented on dag_in_context/src/utility/subst.egg
> +         (Alloc id (Subst (- fuel 1) assum to c1) (Subst fuel assum to state) ty)
Should decrease both fuels

2024-04-11 21:37 UTC, kirstenmg requested changes

2024-04-11 21:37 UTC, kirstenmg commented on dag_in_context/src/utility/subst.egg
Shouldn't we stop substituting when the fuel gets to 0? I don't see where that happens in these rules.

2024-04-11 21:38 UTC, kirstenmg commented on dag_in_context/src/utility/subst.egg
Related to this, I think there should be a test for a non-infinite fuel, e.g. a fuel of 2

2024-04-12 17:31 UTC, oflatt commented
Don't forget to request a review when this is ready

2024-04-12 21:46 UTC, merged