Add some basic peepholes
egraphs-good/eggcc pull request #523
Opened 2024-05-01 06:17 UTC by ezrosent

This change starts a basic peephole optimization files. Most moderately complex peepholes I've found rely on things like shifting operators, sign extensions, etc. None of those can be done at the bril level (but note that LLVM will take advantage of them with optimizations turned on!)

Still, these probably don't hurt. I've added in some rules for forwarding predicates for ifs. Let me know if I'm using contexts correctly here.

2024-05-01 18:12 UTC, oflatt requested changes
One concern- I noticed you added the ruleset to the "saturating" ruleset.
Are we completely certain these always saturate? I think it would be safer to add them to the "optimizations" ruleset, or a new "pre-optimizations" ruleset

2024-05-02 02:24 UTC, ezrosent commented
Done! I think these ones do saturate but in general they may not. Also optimizations is a better description of what the goal is.

2024-05-02 03:13 UTC, ezrosent commented
Looks like there's a failing test: `loop_invariant::test_invariant_detect` 

I'll take a look

2024-05-02 20:23 UTC, oflatt approved these changes
Yay!

2024-05-05 06:06 UTC, merged